### ISSUE TITLE
1.18.2 Sky and Oregen in Demon realm

### ISSUE THREAD

**Issue by gabEHTM** [dkmk100/ArsOmega#11]
The sky in the demon realm is not red as shown in the pictures on curseforge, and the demonic rifts are not generating in the dimension. 

I do know that the Demon realm is a WIP but I just wanted to make sure it's on your radar

**Comment by dkmk100** [comment]
I'll look into the sky, that is sorta funky.
In the most recent version, demonic rifts do spawn, just underground. I updated the worn notebook to mention this.

**Comment by dkmk100** [comment]
will be fixed next beta

**Comment by dkmk100** [comment]
fixed in beta 5 I think
