### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by tomko157** [dkmk100/ArsOmega#12]
Hello,

I updated Ars Omega from 2.4.0 to 2.6.0 on my server and suddenly I can't connect anymore, I get this error:
Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceLocation.toString()" because "p_130086_" is null

The server loads correctly and I can play singleplayer just fine. Could you please look into it?

**Comment by dkmk100** [comment]
Hmm, I seem to have messed up one of my recipe serializers. I'm looking into it now, will try to push a fix today. Sorry about that!

**Comment by dkmk100** [comment]
found a fix, will upload now

**Comment by dkmk100** [comment]
Fixed in version 2.6.1:
https://www.curseforge.com/minecraft/mc-mods/ars-omega/files/3819746
