### ISSUE TITLE
creative spellbook cannot use tier4 spells

### ISSUE THREAD

**Issue by lordi-erez** [dkmk100/ArsOmega#17]
i wanna mess around imn creative mode, but i can't mess w/ new spells

**Comment by dkmk100** [comment]
that's technically an issue with base ars, but I'll try and see if I can find a workaround myself.

**Comment by LIAM1543** [comment]
the latest update on base ars nouveau allows the creative spell book to cast up to tier 99 glyphs, give it a shot
