### ISSUE TITLE
Empty NBT tag causing items to not stack

### ISSUE THREAD

**Issue by NonIntelligent** [dkmk100/ArsOmega#18]
Opening a chest while holding an item adds an empty NBT tag to it and so it doesn't stack with other items. Obtaining items through the creative menu also applies the empty tag.
I found that this issue is present in the 2.7.0 beta jars and not on the 2.6.1 release.

**Comment by drakray** [comment]
I got something like that too, but randomly with any items, and when placing block
example, I have 8 torches in my bar, I place 2, break them, they don't stack with the 6 others.
dropping them all in the same spot will merge them, but repeating the process will make separated stack again
there is no apparent NBT data though, as '/ct hand' from CraftTweaker don't show any, nor any commands from other mods to identify hold stack

Removing ArsOmega (2.7.0 beta-2) completely from my modPack fixes the problem
Reverting to 2.7.0 beta-1, problem still exist
Reverting to 2.6.1 seems to fix/no cause the problem(though I had to place and break for the 2 stack to merge)

**Comment by NonIntelligent** [comment]
Exactly as you described as it only affects items that don't have a tag in the first place. I used the `/data get entity @p SelectedItem` command and saw the extra tag as `tag: {}`. The torches when broken drop without the tag but can stack with other torches on the ground and all will have the empty tag.

**Comment by dkmk100** [comment]
yea, I'll fix that in beta 3. Sorry, I'm using a .getOrCreateTag where I REALLY shouldn't lol.

**Comment by ZephyrWindSpirit** [comment]
I'm here to let you know that beta 3 still has this issue occurring. Sticks and torches were what I'm seeing the empty tag with, so they don't stack between drops and crafting. 
2.7.0 beta 3 with ars nouveau 2.6.0 on forge 40.1.52 with Direwolf20 1.18.2 1.6.1
FINALLY narrowed it down, this took all day from 30+ added mods on another instance. 

Checking now that the sticks stack again with 2.6.1... yeah, they're fine. had to trash the sticks made with the betas to get them to stack again.

**Comment by dkmk100** [comment]
hmm, that's odd...

**Comment by dkmk100** [comment]
ok so I found the second cause location, in the client on tooltip, and fixed it there too. Should definitely be fixed in beta 4, or whatever I call the next upload.

**Comment by JericNisperos** [comment]
Experienced a different bug but related to this, I'm playing with modpack and recently added the Ars Omega 2.7.0 and noticed an issue regarding with my Refined Storage, not only that but most of my GUI mods as well like Toms Simple Storage Mod. Reverted it back to 2.6.1 and the bug disappeared.

**Comment by NonIntelligent** [comment]
Looks like Item stacking is fixed with beta4, thanks for this.

**Comment by dkmk100** [comment]
hopefully my fix on beta 4 finally ends this for good, if not feel free to create another issue for it.
