### ISSUE TITLE
Wizard Tower generates incorrectly

### ISSUE THREAD

**Issue by brisingraerowing** [dkmk100/ArsOmega#19]
A picture is worth a thousand words, so:

![2022-07-02_19 02 20](https://user-images.githubusercontent.com/250409/177018446-11da6381-7860-484d-b9a9-4273c78c0f84.png)

Also, the spawner hidden in the 'basement' doesn't seem to have been created correctly as it spawns pigs.

**Comment by dkmk100** [comment]
yea it needs a lot of help lol, a trap at the top also seems to malfunction...
I'll look into it soon, will probably just give up on using datapacks and go back to hardcoding it...

**Comment by Shadowex3** [comment]
Ran into one of these right by my spawn in a new world and without the traps or any mobs I immediately felt like I was cheating. Just had buckets of gold and fantastic OP loot with no risk on my part.

**Comment by dkmk100** [comment]
mostly fixed in pre release, I'll make a new issue for lack of trap at the top
