### ISSUE TITLE
Server crashes when summoning Demon king.

### ISSUE THREAD

**Issue by Pyruus3** [dkmk100/ArsOmega#2]
Hi, we're not sure what's going on, or why, but everytime we attempt to summon the Demon King, the server crashes, Sometimes, clients crash, too.
[crash-2022-04-17_21.52.23-server.txt](https://github.com/dkmk100/ArsOmega/files/8502322/crash-2022-04-17_21.52.23-server.txt)

**Comment by dkmk100** [comment]
Is this on version 1.1 of the mod? There might have been an issue in version 1.0 which I fixed...

If it is on the most recent version, let me know and I can put a fix up on curseforge in the next day or two.

**Comment by dkmk100** [comment]
nevermind lol, I just looked at the code and noticed I did something dumb. Will fix as soon as possible. 
Sorry about the inconvenience!

**Comment by dkmk100** [comment]
fixed
