### ISSUE TITLE
Overflow Condition in Flatten Spell With Bedrock

### ISSUE THREAD

**Issue by KirinDave** [dkmk100/ArsOmega#22]
Firstly: Flatten currently picks the block below the block the player is standing on.

If you use Flatten while standing over 2 pieces of bedrock causes a damage event that does no damage, and then makes you subsequently immune to all damage forever. I suspect this is an overflow condition somewhere, but it makes the player resistant to even /kill commands.

This is particularly troublesome if a player were to fall into the void. They would be unaffected by void fog and crash the server.

**Comment by dkmk100** [comment]
fixed with 2.7 beta 4 on 1.18, and fixed in dev version on 1.16
