### ISSUE TITLE
[1.18.2] Crashing when joining server

### ISSUE THREAD

**Issue by DiZeroX** [dkmk100/ArsOmega#26]
I have a server with only these mods: 
![image](https://user-images.githubusercontent.com/17834658/187777676-5c214202-8058-4ea3-a8f1-f3080e8c8c10.png)

The server crashes when a client tries to access the server. 

![image](https://user-images.githubusercontent.com/17834658/187778894-02e19310-67b5-4364-80b4-a0e04f2883e2.png)

[debug.log](https://github.com/dkmk100/ArsOmega/files/9464862/debug.log)

**Comment by dkmk100** [comment]
did the server ever work, or was this error on first startup?

are you using forge or something else to launch the game?
