### ISSUE TITLE
Error Using missing texture

### ISSUE THREAD

**Issue by hainkiwanki** [dkmk100/ArsOmega#29]
I get some errors during minecraft startup:
https://pastebin.com/e9zX8pKu

Mods Installed:
![image](https://user-images.githubusercontent.com/1174451/193656834-e8bb4877-cd72-46f4-9c31-b6823c444f94.png)

**Comment by dkmk100** [comment]
yea, spawn eggs have no textures

**Comment by dkmk100** [comment]
will be fixed in next 1.19 release, and I don't think I'm updating 1.18 anymore

**Comment by dkmk100** [comment]
fixed in 3.1.0 for 1.19, and won't fix in 1.18
