### ISSUE TITLE
1.19.2 Crashing when booting a curseforge modpack with Ars Nouveau, Elemental, Omega

### ISSUE THREAD

**Issue by cazeyexe** [dkmk100/ArsOmega#40]
After updating Nouveau to the newest update available on curseforge, whenever I have Omega installed the game will crash on launch. It boots completely fine when I tried booting without Omega installed in the mod pack.
Crash report below 

[crash-2023-01-23_16.00.39-client.txt](https://github.com/dkmk100/ArsOmega/files/10483613/crash-2023-01-23_16.00.39-client.txt)

**Comment by dkmk100** [comment]
I'm aware, downgrade Ars Nouveau to the previous version. I'll fix this as soon as I can, the Ars update broke something.

**Comment by dkmk100** [comment]
hmm, I thought this was something else but I actually have no idea what this is.

**Comment by dkmk100** [comment]
this... is a crash with the NEW most recent version of ars. The last two updates to ars managed to both create new crashes with Omega lol.

Downgrade to Ars Nouveau 3.8.1, and I'll fix this issue as soon as possible.

**Comment by dkmk100** [comment]
fixed in alpha 2 I think
