### ISSUE TITLE
Game crashes after adding Omega to ATM8

### ISSUE THREAD

**Issue by NekoLeila** [dkmk100/ArsOmega#41]
[crash-2023-01-29_15.47.39-client.txt](https://github.com/dkmk100/ArsOmega/files/10530833/crash-2023-01-29_15.47.39-client.txt)
[latest.log](https://github.com/dkmk100/ArsOmega/files/10530835/latest.log)

**Comment by dkmk100** [comment]
update both Ars Omega and Ars Nouveau to the latest versions, that should fix the issue

your version of Ars Nouveau is too old, some things changed.

**Comment by dkmk100** [comment]
let me know if that fixes it

**Comment by NekoLeila** [comment]
The launcher is saying this is the latest version of omega available to use in the mod pack, but I updated Ars Nouveau and that solved it, thank you :) 

BTW, some textures are missing, the spawn eggs and the absorption glyph

**Comment by dkmk100** [comment]
Glad you got it to work!

yea, I know about the textures, I just haven't gotten around to fixing them.
