### ISSUE TITLE
there are no tier 4 armors in my game

### ISSUE THREAD

**Issue by Ngnlant** [dkmk100/ArsOmega#44]
There are no tier 4 armors in my game, I try to reinstall the mod in different clients but no change.(gamemode creative)
And everything else works normally.

mc version 1.18.2 , mod version 2.7.2

[latest.log](https://github.com/dkmk100/ArsOmega/files/10559648/latest.log)

**Comment by dkmk100** [comment]
I think I straight up accidentally deleted the armors from the mod. I'm archiving version 2.7.2 on curseforge so nobody else downloads it, and will try to upload a fix tonight. Oops, and thanks for catching the issue!

**Comment by dkmk100** [comment]
does the new version work right for you too?

**Comment by Ngnlant** [comment]
yes!

**Comment by dkmk100** [comment]
alright, that's done with then
