### ISSUE TITLE
[1.19.2] Ritual of Shaping Crashes

### ISSUE THREAD

**Issue by RikuTheKiller** [dkmk100/ArsOmega#46]
I've made a temporary fix for this in the form of a CraftTweaker script that replaces the ritual of shaping:
```
<recipetype:arsomega:sigil>.removeAll();
craftingTable.addShapeless("sigil_water_active", <item:arsomega:sigil_water_active>, [<item:arsomega:ritual_shaping>, <item:ars_nouveau:water_essence>, <item:arsomega:chalk>]);
craftingTable.addShapeless("sigil_fire_active", <item:arsomega:sigil_fire_active>, [<item:arsomega:ritual_shaping>, <item:ars_nouveau:fire_essence>, <item:arsomega:chalk>]);
craftingTable.addShapeless("sigil_earth_active", <item:arsomega:sigil_earth_active>, [<item:arsomega:ritual_shaping>, <item:ars_nouveau:earth_essence>, <item:arsomega:chalk>]);
craftingTable.addShapeless("sigil_air_active", <item:arsomega:sigil_air_active>, [<item:arsomega:ritual_shaping>, <item:ars_nouveau:air_essence>, <item:arsomega:chalk>]);
craftingTable.addShapeless("sigil_binding_active", <item:arsomega:sigil_binding_active>, [<item:arsomega:ritual_shaping>, <item:arsomega:demonic_essence>, <item:arsomega:chalk>]);
craftingTable.addShapeless("sigil_alchemy_active", <item:arsomega:sigil_alchemy_active>, [<item:arsomega:ritual_shaping>, <item:arsomega:alchemy_essence>, <item:arsomega:chalk>]);
craftingTable.addShapeless("sigil_life_active", <item:arsomega:sigil_life_active>, [<item:arsomega:ritual_shaping>, <item:arsomega:life_essence>, <item:arsomega:chalk>]);
craftingTable.addShapeless("sigil_nature_active", <item:arsomega:sigil_nature_active>, [<item:arsomega:ritual_shaping>, <item:arsomega:nature_essence>, <item:arsomega:chalk>]);
```
To add it, simply put it in a ZenScript file of your choice.

**Comment by dkmk100** [comment]
that crash just means something froze, and a single tick took a whole minute. I have no way of knowing what caused it or even if it was caused by the ritual of shaping.

**Comment by dkmk100** [comment]
do you have any other useful information? can you reproduce it without all the other mods?

**Comment by RikuTheKiller** [comment]
It happened immediately after I put down the last chalk for sigil of alchemy.

**Comment by RikuTheKiller** [comment]
I'll try reproducing it again, however it's 4:31 AM and I don't feel like messing with my files atm.

**Comment by dkmk100** [comment]
huh, can you test if it happens in a new world?

**Comment by RikuTheKiller** [comment]
I can test that, but first, second try on the server.

**Comment by RikuTheKiller** [comment]
Seems... the bug has locked me out of my server.

**Comment by RikuTheKiller** [comment]
Joining immediately loads the bugged ritual which crashes the server.

**Comment by dkmk100** [comment]
figured, something seems stuck in an infinite loop. I'll look and see if I can find it, but see if it happens on a new creative world.

**Comment by dkmk100** [comment]
oh wait this is on 1.19... huh

**Comment by RikuTheKiller** [comment]
Yeah... the latest alpha release.

**Comment by RikuTheKiller** [comment]
It's not like I didn't expect bugs (cough cough worn notebook titles) but uh, this one is quite bad.

**Comment by dkmk100** [comment]
oh, can you create a separate github issue saying witch worn notebook title is broken?

**Comment by RikuTheKiller** [comment]
Which? Every.

**Comment by dkmk100** [comment]
I wouldn't be surprised if I goofed up something on the 1.19 version lol, it is probably an omega issue then

**Comment by RikuTheKiller** [comment]
Almost every single omega one is goofed.

**Comment by RikuTheKiller** [comment]
For example, patterns.

**Comment by dkmk100** [comment]
> Which? Every.

lol, ok, that's funky

**Comment by RikuTheKiller** [comment]
Hmm, didn't happen on the fresh world.

**Comment by RikuTheKiller** [comment]
Yeah, it seems to only happen on the server.

**Comment by RikuTheKiller** [comment]
This may be an incompatibility with a server-side mod.

**Comment by RikuTheKiller** [comment]
Question is... which one?

**Comment by dkmk100** [comment]
oh, it could be, which of those do you have?

**Comment by RikuTheKiller** [comment]
Chunky
Connectivity
FerriteCore
Radium
Spark
Starlight

These are the only ones I could see causing a problem.

**Comment by RikuTheKiller** [comment]
Spark would be a weird one, though.

**Comment by RikuTheKiller** [comment]
Right, you can also see the mod list. I have a mod for more advanced crash reports.

**Comment by RikuTheKiller** [comment]
Oh, I have a great idea. Spark.

**Comment by dkmk100** [comment]
yea use spark to find the problem if possible, sometimes it helps lol

**Comment by dkmk100** [comment]
if you get a chance tomorrow, it's also worth checking if removing the performance mods fixes the problem or if it's still there without them.

**Comment by RikuTheKiller** [comment]
I don't think I can use spark for this, so sad.

**Comment by dkmk100** [comment]
might not be able to I guess, if it's completely stuck

**Comment by RikuTheKiller** [comment]
I'm going to try without the performance mods rn.

**Comment by RikuTheKiller** [comment]
Crashed.

**Comment by RikuTheKiller** [comment]
For context, the ritual was in a running state and the game crashed the moment I put the last chalk in for the sigil of alchemy.

**Comment by dkmk100** [comment]
still same crash report? server watchdog?

**Comment by RikuTheKiller** [comment]
Yes.

**Comment by dkmk100** [comment]
I haven't heard anyone else have issues and I have no idea what caused this.
