### ISSUE TITLE
Arcane Spellbook is held upside-down

### ISSUE THREAD

**Issue by Randommnumbers** [dkmk100/ArsOmega#47]
With arsomega-3.0.0-alpha-2 for the 1.19 version, the Arcane Spellbook is held upside-down in the hand. With the cover of the book towards the camera and the pages facing downwards. Due to the positioning being closer to the camera, this covers around 50% more screen space than the Nouveau spell books. Looks hilarious, but I don't think this is intentional.
![image](https://user-images.githubusercontent.com/41096451/216803766-1c04b974-e534-481d-b0d2-417611d871dc.png)
![image](https://user-images.githubusercontent.com/41096451/216803792-272c5a5d-86af-4868-b0b0-00ab94e62753.png)

**Comment by dkmk100** [comment]
fixed
