### ISSUE TITLE
[1.19.2] Alchemical Diamond Block Recipe Conflict

### ISSUE THREAD

**Issue by RikuTheKiller** [dkmk100/ArsOmega#48]
The recipe for alchemical diamond blocks conflicts with the vanilla diamond block recipe and it defaults to the alchemical ones. I had to modify it via CraftTweaker.

**Comment by dkmk100** [comment]
can you clarify what you mean by this?

**Comment by Earlh21** [comment]
9 diamonds is supposed to create a normal, vanilla diamond block. This mod overwrites that recipe with the alchemical diamond block which cannot be used in many recipes that require a diamond block.

**Comment by uhloin** [comment]
As temporary solution I opened .jar file as archive and deleted file inside:
\data\forge\tags\items\gems\diamond.json

**Comment by dkmk100** [comment]
which mod version are you guys on?

**Comment by uhloin** [comment]
I've just updated to version arsomega-3.1.0-alpha-1.jar and have not tested it yet. So, bug was in previous version for forge 1.19.2.

**Comment by uhloin** [comment]
arsomega-3.1.0-alpha-1.jar version also contains this bug

**Comment by dkmk100** [comment]
um.... I can't replicate the issue, and checking the mod files this literally isn't the case. The alchemical diamond block is made specifically with alchemical diamonds. What's your mod list? Do you have any datapacks, are you playing a modpack, or are you playing on a server? I'd need info about those too

**Comment by uhloin** [comment]
I use big random mod list, but probably this is not a problem from some mod conflict.
I'm not sure, but .jar contains the file:
\data\forge\tags\items\gems\diamond.json 
May be it sets tag "arsomega:alchemical_diamond" tag to normal diamond and later normal diamond is used as alchemical and produces alchemical?
At least, if I remove this file, bug disappears.

**Comment by uhloin** [comment]
Some mods that be involved:
arsomega-3.1.0-alpha-1.jar 
jei-1.19.2-forge-11.6.0.1018.jar 
ars_nouveau-1.19.2-3.17.10.jar 
ars_elemental-1.19.2-0.5.9.1.2b.jar 
geckolib-forge-1.19-3.1.40.jar

**Comment by dkmk100** [comment]
I have no idea what to make of this, but I can confirm that with just the mods you listed it works as intended so I don't think there's anything else I can do without more info
