### ISSUE TITLE
Ars Omega book entries are stubs/placeholders in 1.19 alpha 2

### ISSUE THREAD

**Issue by GrifVindh** [dkmk100/ArsOmega#49]
This may be already known - just a byproduct of the release being alpha - but on the off-chance that the content for all the new spells should be included in the worn notebook/spellbook notes, it looks like at the moment this isn't the case. There are entries for all the new glyphs for Tier 1, Tier 2, and Tier 3 spells, but all they do is list the raw name for the spell (not the in-game name) and don't provide descriptions. Also, there is no entry at all for the Tier 4 spells.

**Comment by dkmk100** [comment]
fixed a few updates ago
