### ISSUE TITLE
issue joining multiplayer in CamaCraft pack

### ISSUE THREAD

**Issue by Camawama** [dkmk100/ArsOmega#54]
![image](https://user-images.githubusercontent.com/43620900/218645334-afc93270-f9ca-49e7-b47a-9b78b46e4b0e.png)
![image](https://user-images.githubusercontent.com/43620900/218645356-8a3323d4-b879-4fca-b271-725738fddb01.png)
[latest-server.log](https://github.com/dkmk100/ArsOmega/files/10728969/latest-server.log)
[latest.log](https://github.com/dkmk100/ArsOmega/files/10728972/latest.log)

**Comment by Camawama** [comment]
(Camacraft is a modpack that I am developing)

**Comment by dkmk100** [comment]
are you using plain forge? other modloaders are unsupported because they break things I can't fix. This looks like youre trying to load plugins, maybe with magma or similar

**Comment by Camawama** [comment]
I am using Magma, yes. 

It's the only good way of running a server like CamaCraft (in my opinion).
