### ISSUE TITLE
Towers in 1.19.2 ver. 3.0.0 alpha 3 are missing blocks.

### ISSUE THREAD

**Issue by GoldenMerc** [dkmk100/ArsOmega#58]
Towers in 1.19.2 ver. 3.0.0 alpha 3 are missing blocks.

**Comment by brisingraerowing** [comment]
![2023-06-13_21 09 24](https://github.com/dkmk100/ArsOmega/assets/250409/fdc424df-60e3-4d38-becb-a0e5d85a708b)

Lots of blocks missing.

**Comment by dkmk100** [comment]
pretty much fixed in 3.1.0 alpha 1
