### ISSUE TITLE
[1.16.5]Multiplayer Incompatibility

### ISSUE THREAD

**Issue by 1keponchem** [dkmk100/ArsOmega#6]
# Version Information
-Minecraft: 1.16.5
-Forge: 36.2.35
-Ars Nouveau: 1.16.5-1.25.0
-Ars Omega: 1.2
# Crash Log
[crash-2022-05-07_11.13.36-fml.txt](https://github.com/dkmk100/ArsOmega/files/8644422/crash-2022-05-07_11.13.36-fml.txt)
# Details
When running a server with Ars Omega and all the depended mods, The server crashes with the log up above.
I think this is because it's using a class that only exists on clients.

**Comment by 1keponchem** [comment]
Also I think the Mod Issue URL in the log is wrong.

**Comment by dkmk100** [comment]
I was able to find the crash, and next update will include a fix.

also, good catch on the issue URL, I never would have found that lol.

**Comment by dkmk100** [comment]
I believe this should be fixed in version 1.3, make a new issue if not.
