### ISSUE TITLE
Focus of Advanced Alchemy unavailable in 1.19.2 Alpha 3 and Alpha 4

### ISSUE THREAD

**Issue by BlueNothing** [dkmk100/ArsOmega#60]
Focus of Advanced Alchemy, Arcane Cloth Armor, and (most likely) Enchanter's Wool Armor are evidently unavailable in (at least the later) 1.19.2 alphas.

The Focus of Advanced Alchemy exists as an item, but cannot be crafted in Survival in 1.19.2, and has no recipe in JEI.
Assembling the requisite ingredients from the Github (2 Enchanted Diamond Blocks, 4 Iron Blocks, and 2 Glyph of Lead Skin) in pedestals directly surrounding the Enchanting Apparatus (1-block radius) and inserting a Focus of Alchemy leads to the report:
"No recipe found. Pedestals must be within 3 blocks," as opposed to the error that would be expected (not enough source, since no source jar was placed for the test).

Crafting a Tier 3 piece of Ars Nouveau armor with Arcane Cloth in the Smithing Table produced no effect in Alpha 3, and the recipe for this upgrade does not appear in JEI for Alpha 3 or Alpha 4.

**Comment by dkmk100** [comment]
the missing recipe is a bug and will be fixed in the next alpha.

tier 4 armor does not exist at this moment and is going to be fully reworked, so I don't really count that as a bug. The references to the armor in the worn notebook do count as bugs but I thought I removed those in Alpha 4. Please let me know if I missed any.

**Comment by BlueNothing** [comment]
Ah, thanks for the update. I'll have to check the notebooks in Alpha 4, I didn't check about armor in Alpha 4 as much. Definitely not a bug, there, then, and the clarification about the Advanced Focus of Alchemy recipe is greatly appreciated. If I remember to look and notice something you missed, I'll let you know, but there's a good chance I'll forget.

**Comment by dkmk100** [comment]
fixed in 3.0.1
