### ISSUE TITLE
disenchant glyph recipe different to book/wiki

### ISSUE THREAD

**Issue by inojakal** [dkmk100/ArsOmega#61]
noticed that the items in the book for disenchant and on the ars omega wiki are vastly different to the actual recipe when making the glyph
![2023-04-26_09 21 38](https://user-images.githubusercontent.com/130875464/234428426-c7ef6994-0a4b-4269-b638-7096b8eec7d9.png)
![2023-04-26_09 21 56](https://user-images.githubusercontent.com/130875464/234428437-feb03a3e-e714-40b8-b4cd-d4da7ce96968.png)

**Comment by dkmk100** [comment]
huh, watch it be something dumb like disenchant showing the enchant recipe lol
I bet it is that actually, looks like it

**Comment by inojakal** [comment]
looks like it, I didn't even see that lol.

**Comment by dkmk100** [comment]
fixed in 3.1.0 alpha 1
