### ISSUE TITLE
Crashes.

### ISSUE THREAD

**Issue by MagmaSlime123** [dkmk100/ArsOmega#62]
Title, see report for modlist.

https://pastebin.com/pYVbxgAS

**Comment by dkmk100** [comment]
Minecraft 1.16 only officially supports Java 8 and thus Ars Omega on 1.16 is made to work with java 8. Try downgrading your java version, there's another issue open with more details I think.

**Comment by MagmaSlime123** [comment]
A mod that I use uses Java 17 for certain reasons (https://modrinth.com/mod/world-host), so I am unable to use Java 8.
