### ISSUE TITLE
Demon Realm missing DimensionType

### ISSUE THREAD

**Issue by Nick1st** [dkmk100/ArsOmega#68]
The dimension `arsomega:demon_realm` is missing a dimension type. This leads to several issues, including but not limited to:

- Breaking the `/forge dimensions` command
- Causing chunkloading problems with Immersive Portals

**Comment by dkmk100** [comment]
mod version?

**Comment by JoelDohmKaratjas** [comment]
I've the same problem

Minecraft: 1.18.2
Ars Omega: 2.7.4
Forge: 40.2.10

**Comment by dkmk100** [comment]
two questions: 
were you on a superflat world?
can you see if relogging fixes the issue?

**Comment by Nick1st** [comment]
The worldtype does not seem to influence the issue in any way. Relogging does not fix the issue.

**Comment by Arasarhood** [comment]
Same issue on 1.18.2

**Comment by dkmk100** [comment]
1.18.2 is no longer supported at this point because keeping up with 1.19 is hard enough. Unless anyone has issues in 1.19 (or a future version) I'm gonna close this as I've only heard issues from 1.18
