### ISSUE TITLE
Biome Crystal only setting biome to minecraft:ocean

### ISSUE THREAD

**Issue by Midlex** [dkmk100/ArsOmega#69]
Using this mod on a custom modpack rn, and the biome crystal only changes to `minecraft:ocean`, It would be nice to have a bit more info on how to use it in the notebook entry, not sure if it's a bug
![imagen](https://github.com/dkmk100/ArsOmega/assets/103068644/80abc8b0-c6f3-4dc7-b988-312d5e2b5937)

**Comment by dkmk100** [comment]
mod version? Can you post the server's latest.log? (or yours if in singleplayer)

**Comment by Midlex** [comment]
mod version is 3.0.1

[latest.log](https://github.com/dkmk100/ArsOmega/files/12266925/latest.log)
[debug.log](https://github.com/dkmk100/ArsOmega/files/12266927/debug.log)

**Comment by dkmk100** [comment]
the biome crystal and ritual of change biome don't work in 1.19 yet, sorry. I'll try to fix it when I get a chance. 

You are probably using it correctly, you just have to right click while in your biome of choice to use it.

**Comment by Midlex** [comment]
Oh okay, thanks, I'll wait for an update then

**Comment by dkmk100** [comment]
fixed in 3.1.0 alpha 1
