### ISSUE TITLE
[1.18.2] Dedicated server crash

### ISSUE THREAD

**Issue by ZEROX7** [dkmk100/ArsOmega#7]
[crash-2022-05-07_16.38.31-fml.txt](https://github.com/dkmk100/ArsOmega/files/8645408/crash-2022-05-07_16.38.31-fml.txt)

**Comment by dkmk100** [comment]
Pretty sure the cause is identical to https://github.com/dkmk100/ArsOmega/issues/6 . If so, I should be able to fix it pretty quickly. I'll see about uploading a fix later today.
