### ISSUE TITLE
Can't communicate the being

### ISSUE THREAD

**Issue by tygotjeeeh** [dkmk100/ArsOmega#70]
I right click the being mirror but nothing happens. Also anyone know how long I have to wait before I offer again?

**Comment by dkmk100** [comment]
Did something happen the first time? What happens when you throw in an unimportant item like an iron ingot? 

It's also still pretty incomplete just so you're aware, especially on 1.19

**Comment by tygotjeeeh** [comment]
something happened the 1st time, he said it had been a long time since it received a gift

**Comment by tygotjeeeh** [comment]
> Did something happen the first time? What happens when you throw in an unimportant item like an iron ingot?
> 
> It's also still pretty incomplete just so you're aware, especially on 1.19

are you supposed to be able to talk to it on 1.19?

**Comment by dkmk100** [comment]
He doesn't do anything unless you throw an item in on 1.18.

On 1.19 its either like that or he doesn't do anything at all. I forgot how far I was porting that.

I can say that next update for 1.19, which will come out in like 2 weeks, will make him do a lot more including respond every time you click.

**Comment by dkmk100** [comment]
"in like two weeks" oops it's been a bit more than that but I'm almost done I promise

**Comment by dkmk100** [comment]
alright, I uploaded the next 1.19 version. There's still a lot more to do with the portal but not sure it's really this issue anymore.
