### ISSUE TITLE
Dedicated Server crashes with Ritual of Change Biome

### ISSUE THREAD

**Issue by LordOfTheHobos** [dkmk100/ArsOmega#72]
[crash-2023-09-29_19.26.48-server.txt](https://github.com/dkmk100/ArsOmega/files/12771400/crash-2023-09-29_19.26.48-server.txt)

Server + Game crashed upon ritual of change biome finishing. Used a biome crystal set to Mirage Isles from Terralith. Assuming its just a compatibility issue, but I have no clue how to fix it

**Comment by dkmk100** [comment]
Do you have any other mods that add biomes? If so, can you test the ritual with a biome from each of those mods and let me know which ones do and don't crash the game?

Not really sure why that's happening

**Comment by dkmk100** [comment]
think I figured it out, and this will be fixed in the next update

**Comment by LordOfTheHobos** [comment]
Alright, Ill just avoid the ritual till then, thanks
