### ISSUE TITLE
Tornado spell cause game crash

### ISSUE THREAD

**Issue by Fabriunion13** [dkmk100/ArsOmega#74]
When i use the tornado spell my game crash

Minecraft: 1.19.2
Ars Omega: 3.1.1
Forge: 43.3.0

[crash-2023-12-20_01.09.08-client.txt](https://github.com/dkmk100/ArsOmega/files/13722847/crash-2023-12-20_01.09.08-client.txt)

**Comment by PG1706** [comment]
Same thing happens to me 

mc 1.19.2
Ars omega 3.1.1
Forge 43.3.5

[crash-2023-12-27_15.51.35-client.txt](https://github.com/dkmk100/ArsOmega/files/13780339/crash-2023-12-27_15.51.35-client.txt)

**Comment by dkmk100** [comment]
try the newest beta, the crash should be fixed there

**Comment by KouroshMclovin** [comment]
Im also still having trouble with this spell as well as the whirlpool, anytime anyone uses it on server it causes those near to crash

**Comment by dkmk100** [comment]
@KouroshMclovin please state what version of Ars Omega you are using, and post the crash report

**Comment by KouroshMclovin** [comment]
@dkmk100 
Version 3.1.1
Mc 1.19.2
[crash-2024-03-24_12.42.26-client.txt](https://github.com/dkmk100/ArsOmega/files/14736596/crash-2024-03-24_12.42.26-client.txt)

^ crash report for Whirlpool

[crash-2024-03-24_12.48.01-client.txt](https://github.com/dkmk100/ArsOmega/files/14736610/crash-2024-03-24_12.48.01-client.txt)

^ crash report for Tornado

Edit: Also thanks for a quick response, appreciate the help and the attention to your work

**Comment by dkmk100** [comment]
pretty sure it's fixed in the newest beta if you're willing to use that. Otherwise the full 3.2 release is still a bit off as I'm still working on some features
