### ISSUE TITLE
Durability Cast Enchant - Does nothing?

### ISSUE THREAD

**Issue by aurorapar** [dkmk100/ArsOmega#76]
I was digging through the source code for what this enchant does, and I can't find any action associated with it other than the enchants class being implemented, and the enchant being registered. Is this a worthless enchant?

**Comment by dkmk100** [comment]
that's because I use mixins to make it change how ars's reactive enchant works, it doesn't work with any other kinds of spells

The code is in here:
https://github.com/dkmk100/ArsOmega/tree/1.19.2-main/src/main/java/com/dkmk100/arsomega/mixin/durabilityCast
