### ISSUE TITLE
Enchanter's wool recipe issue

### ISSUE THREAD

**Issue by Keltas** [dkmk100/ArsOmega#8]
When crafting Enchanter's wool armor, the archmage's hood + wool has two recipe outcomes - one for hood and one for shoes. This results in crafting shoes and as such you cannot craft hood at all. archmage shoes on the other hand have no recipe.

**Comment by dkmk100** [comment]
Yea, I found that earlier and completely forgot to fix it. I'll do that now.

**Comment by dkmk100** [comment]
fixed for 1.16.5 in ars omega 1.4.0, still need to fix on 1.18

**Comment by dkmk100** [comment]
version 2.3.0 fixes this on 1.18.2, should now be fixed everywhere.
